# http://rosreestr.ru/fir_lite_rest/api/gkn/fir_lite_object/52:18:0070179:1082
# https://rosreestr.ru/fir_rest/api/fir/fir_objects/52:18:0070179:1082
https://rosreestr.ru/fir_rest/api/fir/fir_egrp_object/152_11254979000
