# Generated by Django 3.1.2 on 2022-01-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Facility',
        ),
        migrations.RenameModel(
            old_name='ObjectType',
            new_name='FacilityType',
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='facilitytype',
            options={'verbose_name': 'Типы', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name': 'Списки', 'verbose_name_plural': 'Списки'},
        ),
        migrations.RemoveField(
            model_name='list',
            name='objects',
        ),
        migrations.AddField(
            model_name='list',
            name='facility',
            field=models.ManyToManyField(related_name='list', to='home.Facility'),
        ),
    ]
